// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.0
//   protoc               v3.20.3
// source: proto/users.proto

/* eslint-disable */

export const protobufPackage = "users";

export const USERS_PACKAGE_NAME = "users";
